### ISSUE TITLE
Why require scales to be integers?

### ISSUE THREAD

**Issue by erickreutz** [davidhellmann/tailwindcss-fluid-type#11]
I see you are doing checks to see whether the values are integers and if they are - returning the value instead of calculating the modular scale. Why is this? Would be nice to have `x.5` scales or any arbitrary scale. If I submitted a PR would you accept it?

**Comment by davidhellmann** [comment]
Hey @erickreutz 

It's simple because the modular scale is a harmonic way to define your fonts. 
With float numbers, you kill that harmony. But I think you're not interested in that modular scale thing and you just like to use fluid type, right? 

But I think it's easy to implement. I'll look into it after my vacation and combine it with the V2 launch. 
If there is a reason to not do it I'll let you know here. 

Thanks!

**Comment by davidhellmann** [comment]
v2 is released with these changes: https://github.com/davidhellmann/tailwindcss-fluid-type/releases/tag/2.0.0
